"""
contracts.py
============
Generic, YAML-driven data contract validation engine.
Adapts to read YAML contracts generated by the agents, running validation checks
over Spark DataFrames using performant aggregated checks.
"""
from __future__ import annotations

import os
import glob
from typing import Dict, Any, List, Tuple

import yaml
from pyspark.sql import DataFrame
from pyspark.sql import functions as F

from .spark_utils import load_config, GENERATED_ROOT

# Spark dtype-string fragments that a numeric `range` rule can legitimately be
# compared against. `dtype` values come from profiling as str(field.dataType),
# e.g. "IntegerType()", "DoubleType()", "DecimalType(10,2)".
_NUMERIC_DTYPE_FRAGMENTS = (
    "ByteType", "ShortType", "IntegerType", "LongType",
    "FloatType", "DoubleType", "DecimalType",
)


def _dtype_is_numeric(dtype_str: str) -> bool:
    return any(frag in (dtype_str or "") for frag in _NUMERIC_DTYPE_FRAGMENTS)


def sanitize_contract_rules(contract: dict, columns: Dict[str, Dict[str, Any]]) -> Tuple[dict, List[str]]:
    """Deterministically reconcile an LLM-authored contract with what the
    profiler actually observed in the source, BEFORE it gets cached/approved and
    used to gate silver promotion. Prevents the two mis-generation patterns that
    cause false HALTs:

      1. A `range` rule attached to a non-numeric or nonexistent column
         (e.g. a numeric 0..1000000 bound on the TIMESTAMP `price_band_start`).
         Such a check can't be evaluated and is dropped.
      2. A hard `not_null` (or any rule) listing a column that the profiler
         shows is legitimately nullable — i.e. its observed null_pct exceeds the
         rule's own max_fail_rate. That column is removed from the not_null list
         so a naturally-nullable field (postcode, region, miles_from_sea, …)
         doesn't halt the whole pipeline. Columns that ARE non-null in the
         source keep their not_null guarantee.

    Also drops any rule reference to a column the profiler never saw. `columns`
    is {col_name: {"dtype": str, "null_pct": float(0-100), "distinct_count": int}}.
    Returns (sanitized_contract, list_of_change_descriptions). The input is not
    mutated. If `columns` is empty (no profile), the contract is returned as-is
    to avoid destroying rules we can't verify."""
    import copy
    contract = copy.deepcopy(contract)
    changes: List[str] = []
    if not columns:
        return contract, changes

    known = set(columns.keys())
    rules = contract.get("rules")
    if not isinstance(rules, dict):
        return contract, changes

    def _max_rate(rule: dict) -> float:
        try:
            return float(rule.get("max_fail_rate", 0.0) or 0.0)
        except (TypeError, ValueError):
            return 0.0

    # --- not_null (and structurally identical column-list rules) ---
    for rule_key in ("not_null", "unique"):
        rule = rules.get(rule_key)
        if isinstance(rule, dict) and isinstance(rule.get("columns"), list):
            max_rate = _max_rate(rule)
            kept = []
            for col in rule["columns"]:
                if col not in known:
                    changes.append(f"{rule_key}: dropped '{col}' (not in source schema)")
                    continue
                if rule_key == "not_null":
                    null_frac = (columns[col].get("null_pct", 0.0) or 0.0) / 100.0
                    if null_frac > max_rate:
                        changes.append(
                            f"not_null: dropped '{col}' — source is {null_frac*100:.1f}% null "
                            f"(> max_fail_rate {max_rate:.2%}); column is legitimately nullable"
                        )
                        continue
                kept.append(col)
            if kept:
                rule["columns"] = kept
            else:
                rules.pop(rule_key, None)
                changes.append(f"{rule_key}: removed entirely (no valid columns left)")

    # --- range: numeric + existing columns only ---
    rg = rules.get("range")
    if isinstance(rg, dict) and isinstance(rg.get("checks"), dict):
        kept_checks = {}
        for col, bounds in rg["checks"].items():
            if col not in known:
                changes.append(f"range: dropped '{col}' (not in source schema)")
                continue
            if not _dtype_is_numeric(columns[col].get("dtype", "")):
                changes.append(
                    f"range: dropped '{col}' — dtype {columns[col].get('dtype')} is not numeric, "
                    f"cannot compare against bounds {bounds}"
                )
                continue
            kept_checks[col] = bounds
        if kept_checks:
            rg["checks"] = kept_checks
        else:
            rules.pop("range", None)
            changes.append("range: removed entirely (no valid numeric columns left)")

    # --- regex: drop refs to nonexistent columns only ---
    rx = rules.get("regex")
    if isinstance(rx, dict) and isinstance(rx.get("checks"), dict):
        kept = {c: v for c, v in rx["checks"].items() if c in known}
        for c in sorted(set(rx["checks"]) - set(kept)):
            changes.append(f"regex: dropped '{c}' (not in source schema)")
        if kept:
            rx["checks"] = kept
        else:
            rules.pop("regex", None)
            changes.append("regex: removed entirely (no valid columns left)")

    # --- allowed_values: drop refs to nonexistent columns AND union in the
    #     profiler's OBSERVED distinct values so real categories the LLM didn't
    #     list aren't silently quarantined. The classic failure: the contract
    #     lists has_pool ∈ {"Yes","No"} while the source actually holds "Y"/"N",
    #     so every row fails a SOFT allowed_values check, gets quarantined, and
    #     silver comes out empty with no HALT to flag it. Profiling captures each
    #     low-cardinality column's real values as `value_counts`; we widen the
    #     allowed set to cover them (never narrowing the LLM's intended domain).
    av = rules.get("allowed_values")
    if isinstance(av, dict) and isinstance(av.get("checks"), dict):
        kept = {}
        for c, allowed in av["checks"].items():
            if c not in known:
                changes.append(f"allowed_values: dropped '{c}' (not in source schema)")
                continue
            observed = {
                v for v in (columns[c].get("value_counts") or {}).keys()
                if v not in ("None", "", "null", "NULL")
            }
            if observed and isinstance(allowed, list):
                missing = observed - set(str(a) for a in allowed)
                if missing:
                    allowed = sorted(set(str(a) for a in allowed) | observed)
                    changes.append(
                        f"allowed_values: widened '{c}' to include observed value(s) "
                        f"{sorted(missing)} (the contract's list didn't cover values "
                        f"actually present in the source)"
                    )
            kept[c] = allowed
        if kept:
            av["checks"] = kept
        else:
            rules.pop("allowed_values", None)
            changes.append("allowed_values: removed entirely (no valid columns left)")

    return contract, changes


def get_contracts_dir() -> str:
    """Find the directory containing the YAML contracts."""
    # 1. Check the shared GENERATED_ROOT path first (same base the agents write to)
    tmp_candidate = os.path.join(GENERATED_ROOT, "config", "contracts")
    if os.path.exists(tmp_candidate):
        return tmp_candidate

    # 2. Fallback: Search workspace directory structures
    cur_dir = os.path.dirname(os.path.abspath(__file__))
    for _ in range(5):
        candidate = os.path.join(cur_dir, "generated", "config", "contracts")
        if os.path.exists(candidate):
            return candidate
        # Check reference implementation fallback during testing
        ref_candidate = os.path.join(cur_dir, "reference_implementation", "config", "contracts")
        if os.path.exists(ref_candidate):
            return ref_candidate
        cur_dir = os.path.dirname(cur_dir)
        
    # Fallback to the shared generated root (created on demand by callers)
    return os.path.join(GENERATED_ROOT, "config", "contracts")


def load_contract(table: str) -> Dict[str, Any]:
    """Load a specific table YAML contract."""
    contracts_dir = get_contracts_dir()
    path = os.path.join(contracts_dir, f"{table}.yaml")
    if not os.path.exists(path):
        raise FileNotFoundError(f"Contract file not found for table '{table}' at path: {path}")
    with open(path) as f:
        return yaml.safe_load(f)


def load_all_contracts() -> Dict[str, Dict[str, Any]]:
    """Load all YAML contracts in the contracts directory."""
    contracts_dir = get_contracts_dir()
    out = {}
    
    # Create the directory if it doesn't exist yet
    if not os.path.exists(contracts_dir):
        os.makedirs(contracts_dir, exist_ok=True)
        return out
        
    for path in glob.glob(os.path.join(contracts_dir, "*.yaml")):
        with open(path) as f:
            c = yaml.safe_load(f)
        if c and "table" in c:
            out[c["table"]] = c
    return out


def _fail_rate(bad_count: int, total: int) -> float:
    return 0.0 if total == 0 else bad_count / total


def validate_table(df: DataFrame, contract: Dict[str, Any], parent_dfs: Dict[str, DataFrame] = None) -> Tuple[DataFrame, DataFrame, Dict[str, Any]]:
    """
    Validates a DataFrame against a contract definition.
    Returns (clean_df, quarantined_df, report).
    
    Rules checked:
      - not_null
      - unique
      - unique_composite
      - allowed_values
      - range
      - regex
      - consistency (raw SQL expressions)
      - referential_integrity (overlaps with parent tables)
    """
    parent_dfs = parent_dfs or {}
    rules = contract.get("rules", {})
    report: Dict[str, Any] = {
        "table": contract["table"],
        "row_count": None,
        "rule_results": [],
        "promotion_blocked": False,
        "quarantined_count": 0,
        "clean_count": 0
    }

    rule_meta: List[tuple] = []
    work = df

    # --- not_null ---
    nn = rules.get("not_null")
    if nn:
        cond = None
        for c in nn["columns"]:
            if c in work.columns:
                this_cond = F.col(c).isNull()
                cond = this_cond if cond is None else (cond | this_cond)
        if cond is not None:
            colname = "_fail_not_null"
            work = work.withColumn(colname, cond)
            rule_meta.append((colname, "not_null", nn["severity"], nn.get("max_fail_rate", 0.0)))

    # --- unique ---
    uq = rules.get("unique")
    if uq:
        for key_col in uq["columns"]:
            if key_col in work.columns:
                dup_vals = work.groupBy(key_col).count().filter(F.col("count") > 1).select(key_col)
                colname = f"_fail_unique_{key_col}"
                work = work.join(dup_vals.withColumn(colname, F.lit(True)), on=key_col, how="left")
                work = work.withColumn(colname, F.coalesce(F.col(colname), F.lit(False)))
                rule_meta.append((colname, f"unique[{key_col}]", uq["severity"], uq.get("max_fail_rate", 0.0)))

    # --- unique_composite ---
    uqc = rules.get("unique_composite")
    if uqc:
        for i, cols in enumerate(uqc.get("column_sets", [])):
            valid_cols = [c for c in cols if c in work.columns]
            if len(valid_cols) == len(cols):
                dup_vals = work.groupBy(*cols).count().filter(F.col("count") > 1).select(*cols)
                colname = f"_fail_unique_composite_{i}"
                work = work.join(dup_vals.withColumn(colname, F.lit(True)), on=cols, how="left")
                work = work.withColumn(colname, F.coalesce(F.col(colname), F.lit(False)))
                rule_meta.append((colname, f"unique_composite{cols}", uqc["severity"], uqc.get("max_fail_rate", 0.0)))

    # --- allowed_values ---
    av = rules.get("allowed_values")
    if av:
        for col, allowed in av.get("checks", {}).items():
            if col in work.columns:
                colname = f"_fail_allowed_{col}"
                work = work.withColumn(colname, ~F.col(col).isin(allowed) & F.col(col).isNotNull())
                rule_meta.append((colname, f"allowed_values[{col}]", av["severity"], av.get("max_fail_rate", 0.0)))

    # --- range ---
    # Range bounds are always numeric (per the contract-generation prompt),
    # but the contract-authoring LLM can still mis-attach a range rule to a
    # non-numeric column — e.g. a TIMESTAMP column whose name merely sounds
    # numeric (a real example: "price_band_start", which is actually a date).
    # Comparing a non-numeric column against a numeric literal raises a hard
    # AnalysisException that kills the entire script, so guard it here:
    # skip that one rule (with a loud warning) instead of crashing silver.py
    # outright. This is a safety net — the real fix is a correct contract.
    _RANGE_NUMERIC_TYPES = (
        "ByteType", "ShortType", "IntegerType", "LongType",
        "FloatType", "DoubleType", "DecimalType",
    )
    rg = rules.get("range")
    if rg:
        for col, bounds in rg.get("checks", {}).items():
            if col in work.columns:
                col_dtype_name = type(work.schema[col].dataType).__name__
                if not any(col_dtype_name.startswith(t) for t in _RANGE_NUMERIC_TYPES):
                    print(
                        f"[Contract Guard] WARNING: Skipping range rule on '{col}' — "
                        f"column dtype is {col_dtype_name}, not numeric, so "
                        f"min/max bounds ({bounds.get('min')}/{bounds.get('max')}) "
                        f"cannot be compared against it. This rule was likely "
                        f"mis-generated for this column — check the contract YAML."
                    )
                    continue
                colname = f"_fail_range_{col}"
                cond = F.col(col).isNotNull() & ((F.col(col) < bounds["min"]) | (F.col(col) > bounds["max"]))
                work = work.withColumn(colname, cond)
                rule_meta.append((colname, f"range[{col}]", rg["severity"], rg.get("max_fail_rate", 0.0)))

    # --- regex ---
    rx = rules.get("regex")
    if rx:
        for col, pattern in rx.get("checks", {}).items():
            if col in work.columns:
                colname = f"_fail_regex_{col}"
                work = work.withColumn(colname, F.col(col).isNotNull() & ~F.col(col).rlike(pattern))
                rule_meta.append((colname, f"regex[{col}]", rx["severity"], rx.get("max_fail_rate", 0.0)))

    # --- consistency (raw SQL boolean expressions; TRUE = pass) ---
    cs = rules.get("consistency")
    if cs:
        for i, check in enumerate(cs.get("checks", [])):
            colname = f"_fail_consistency_{check['name']}"
            work = work.withColumn(colname, ~F.expr(check["expression"]))
            rule_meta.append((colname, f"consistency[{check['name']}]", cs["severity"], cs.get("max_fail_rate", 0.0)))

    # --- referential_integrity ---
    ri = rules.get("referential_integrity")
    if ri and isinstance(ri, dict):
        for check in ri.get("checks", []):
            if check["column"] in work.columns:
                parent_df = parent_dfs.get(check["parent_table"])
                if parent_df is None:
                    continue
                colname = f"_fail_ri_{check['column']}"
                parent_keys = parent_df.select(F.col(check["parent_column"]).alias(check["column"])).distinct()
                work = work.join(parent_keys.withColumn(colname, F.lit(False)), on=check["column"], how="left")
                null_ok = check.get("nullable", False)
                fail_expr = F.col(colname).isNull()
                if null_ok:
                    fail_expr = fail_expr & F.col(check["column"]).isNotNull()
                work = work.withColumn(colname, fail_expr)
                rule_meta.append((colname, f"referential_integrity[{check['column']}->{check['parent_table']}]", ri["severity"], ri.get("max_fail_rate", 0.0)))

    bad_masks = [m[0] for m in rule_meta]

    if bad_masks:
        any_fail = None
        for c in bad_masks:
            any_fail = F.col(c) if any_fail is None else (any_fail | F.col(c))
        work = work.withColumn("_any_fail", any_fail)
        

        agg_exprs = [F.count(F.lit(1)).alias("_total"), F.sum(F.col("_any_fail").cast("long")).alias("_total_bad")]
        agg_exprs += [F.sum(F.col(c).cast("long")).alias(c) for c in bad_masks]
        
        agg_row = work.agg(*agg_exprs).collect()[0]
        total = agg_row["_total"]
        report["row_count"] = total

        for colname, label, severity, max_fail_rate in rule_meta:
            bad_count = agg_row[colname] or 0
            rate = _fail_rate(bad_count, total)
            blocked = severity == "hard" and rate > max_fail_rate
            report["rule_results"].append({
                "rule": label,
                "severity": severity,
                "bad_count": bad_count,
                "fail_rate": round(rate, 4),
                "blocked": blocked
            })
            report["promotion_blocked"] = report["promotion_blocked"] or blocked

        # Human-readable reason naming EXACTLY which hard rule(s) blocked
        # promotion and at what rate — so the silver.py RuntimeError and the
        # final report say "not_null[postcode] failed 12.5% > 0.0%" instead of a
        # generic "hard rule failure" the reviewer then has to go dig for.
        _blocking = [
            f"{r['rule']} failed {r['fail_rate']*100:.2f}% (> allowed "
            f"{next((m[3] for m in rule_meta if m[1] == r['rule']), 0.0)*100:.2f}%)"
            for r in report["rule_results"] if r["blocked"]
        ]
        report["blocking_reason"] = "; ".join(_blocking) if _blocking else ""

        reason_cols = [F.when(F.col(c), F.lit(c.replace("_fail_", ""))) for c in bad_masks]
        work = work.withColumn(
            "_quarantine_reasons", 
            F.array_join(F.array_except(F.array(*reason_cols), F.array(F.lit(None).cast("string"))), ";")
        )
        
        quarantined = work.filter(F.col("_any_fail")).drop(*bad_masks, "_any_fail")
        clean = work.filter(~F.col("_any_fail")).drop(*bad_masks, "_any_fail", "_quarantine_reasons")

        report["quarantined_count"] = agg_row["_total_bad"] or 0
        report["clean_count"] = total - report["quarantined_count"]
    else:
        total = work.count()
        report["row_count"] = total
        quarantined = work.limit(0)
        clean = work
        report["quarantined_count"] = 0
        report["clean_count"] = total

    return clean, quarantined, report


def summarize_reports(reports: List[Dict[str, Any]]) -> Dict[str, Any]:
    """Compile validation reports from multiple tables into a single summary."""
    return {
        "tables_validated": len(reports),
        "any_promotion_blocked": any(r["promotion_blocked"] for r in reports),
        "total_rows": sum(r["row_count"] for r in reports if r["row_count"] is not None),
        "total_quarantined": sum(r["quarantined_count"] for r in reports),
        "details": reports,
    }
