"""
contracts.py
============
Generic, YAML-driven data contract validation engine.
Adapts to read YAML contracts generated by the agents, running validation checks
over Spark DataFrames using performant aggregated checks.
"""
from __future__ import annotations

import os
import glob
from typing import Dict, Any, List, Tuple

import yaml
from pyspark.sql import DataFrame
from pyspark.sql import functions as F

from .spark_utils import load_config

def get_contracts_dir() -> str:
    """Find the directory containing the YAML contracts."""
    # 1. Check the /tmp/generated path first (always used in Databricks environments)
    tmp_candidate = "/tmp/generated/config/contracts"
    if os.path.exists(tmp_candidate):
        return tmp_candidate

    # 2. Fallback: Search workspace directory structures
    cur_dir = os.path.dirname(os.path.abspath(__file__))
    for _ in range(5):
        candidate = os.path.join(cur_dir, "generated", "config", "contracts")
        if os.path.exists(candidate):
            return candidate
        # Check reference implementation fallback during testing
        ref_candidate = os.path.join(cur_dir, "reference_implementation", "config", "contracts")
        if os.path.exists(ref_candidate):
            return ref_candidate
        cur_dir = os.path.dirname(cur_dir)
        
    # Fallback to local default relative path
    return "./generated/config/contracts"


def load_contract(table: str) -> Dict[str, Any]:
    """Load a specific table YAML contract."""
    contracts_dir = get_contracts_dir()
    path = os.path.join(contracts_dir, f"{table}.yaml")
    if not os.path.exists(path):
        raise FileNotFoundError(f"Contract file not found for table '{table}' at path: {path}")
    with open(path) as f:
        return yaml.safe_load(f)


def load_all_contracts() -> Dict[str, Dict[str, Any]]:
    """Load all YAML contracts in the contracts directory."""
    contracts_dir = get_contracts_dir()
    out = {}
    
    # Create the directory if it doesn't exist yet
    if not os.path.exists(contracts_dir):
        os.makedirs(contracts_dir, exist_ok=True)
        return out
        
    for path in glob.glob(os.path.join(contracts_dir, "*.yaml")):
        with open(path) as f:
            c = yaml.safe_load(f)
        if c and "table" in c:
            out[c["table"]] = c
    return out


def _fail_rate(bad_count: int, total: int) -> float:
    return 0.0 if total == 0 else bad_count / total


def validate_table(df: DataFrame, contract: Dict[str, Any], parent_dfs: Dict[str, DataFrame] = None) -> Tuple[DataFrame, DataFrame, Dict[str, Any]]:
    """
    Validates a DataFrame against a contract definition.
    Returns (clean_df, quarantined_df, report).
    
    Rules checked:
      - not_null
      - unique
      - unique_composite
      - allowed_values
      - range
      - regex
      - consistency (raw SQL expressions)
      - referential_integrity (overlaps with parent tables)
    """
    parent_dfs = parent_dfs or {}
    rules = contract.get("rules", {})
    report: Dict[str, Any] = {
        "table": contract["table"],
        "row_count": None,
        "rule_results": [],
        "promotion_blocked": False,
        "quarantined_count": 0,
        "clean_count": 0
    }

    rule_meta: List[tuple] = []
    work = df

    # --- not_null ---
    nn = rules.get("not_null")
    if nn:
        cond = None
        for c in nn["columns"]:
            if c in work.columns:
                this_cond = F.col(c).isNull()
                cond = this_cond if cond is None else (cond | this_cond)
        if cond is not None:
            colname = "_fail_not_null"
            work = work.withColumn(colname, cond)
            rule_meta.append((colname, "not_null", nn["severity"], nn.get("max_fail_rate", 0.0)))

    # --- unique ---
    uq = rules.get("unique")
    if uq:
        for key_col in uq["columns"]:
            if key_col in work.columns:
                dup_vals = work.groupBy(key_col).count().filter(F.col("count") > 1).select(key_col)
                colname = f"_fail_unique_{key_col}"
                work = work.join(dup_vals.withColumn(colname, F.lit(True)), on=key_col, how="left")
                work = work.withColumn(colname, F.coalesce(F.col(colname), F.lit(False)))
                rule_meta.append((colname, f"unique[{key_col}]", uq["severity"], uq.get("max_fail_rate", 0.0)))

    # --- unique_composite ---
    uqc = rules.get("unique_composite")
    if uqc:
        for i, cols in enumerate(uqc.get("column_sets", [])):
            valid_cols = [c for c in cols if c in work.columns]
            if len(valid_cols) == len(cols):
                dup_vals = work.groupBy(*cols).count().filter(F.col("count") > 1).select(*cols)
                colname = f"_fail_unique_composite_{i}"
                work = work.join(dup_vals.withColumn(colname, F.lit(True)), on=cols, how="left")
                work = work.withColumn(colname, F.coalesce(F.col(colname), F.lit(False)))
                rule_meta.append((colname, f"unique_composite{cols}", uqc["severity"], uqc.get("max_fail_rate", 0.0)))

    # --- allowed_values ---
    av = rules.get("allowed_values")
    if av:
        for col, allowed in av.get("checks", {}).items():
            if col in work.columns:
                colname = f"_fail_allowed_{col}"
                work = work.withColumn(colname, ~F.col(col).isin(allowed) & F.col(col).isNotNull())
                rule_meta.append((colname, f"allowed_values[{col}]", av["severity"], av.get("max_fail_rate", 0.0)))

    # --- range ---
    rg = rules.get("range")
    if rg:
        for col, bounds in rg.get("checks", {}).items():
            if col in work.columns:
                colname = f"_fail_range_{col}"
                cond = F.col(col).isNotNull() & ((F.col(col) < bounds["min"]) | (F.col(col) > bounds["max"]))
                work = work.withColumn(colname, cond)
                rule_meta.append((colname, f"range[{col}]", rg["severity"], rg.get("max_fail_rate", 0.0)))

    # --- regex ---
    rx = rules.get("regex")
    if rx:
        for col, pattern in rx.get("checks", {}).items():
            if col in work.columns:
                colname = f"_fail_regex_{col}"
                work = work.withColumn(colname, F.col(col).isNotNull() & ~F.col(col).rlike(pattern))
                rule_meta.append((colname, f"regex[{col}]", rx["severity"], rx.get("max_fail_rate", 0.0)))

    # --- consistency (raw SQL boolean expressions; TRUE = pass) ---
    cs = rules.get("consistency")
    if cs:
        for i, check in enumerate(cs.get("checks", [])):
            colname = f"_fail_consistency_{check['name']}"
            work = work.withColumn(colname, ~F.expr(check["expression"]))
            rule_meta.append((colname, f"consistency[{check['name']}]", cs["severity"], cs.get("max_fail_rate", 0.0)))

    # --- referential_integrity ---
    ri = rules.get("referential_integrity")
    if ri and isinstance(ri, dict):
        for check in ri.get("checks", []):
            if check["column"] in work.columns:
                parent_df = parent_dfs.get(check["parent_table"])
                if parent_df is None:
                    continue
                colname = f"_fail_ri_{check['column']}"
                parent_keys = parent_df.select(F.col(check["parent_column"]).alias(check["column"])).distinct()
                work = work.join(parent_keys.withColumn(colname, F.lit(False)), on=check["column"], how="left")
                null_ok = check.get("nullable", False)
                fail_expr = F.col(colname).isNull()
                if null_ok:
                    fail_expr = fail_expr & F.col(check["column"]).isNotNull()
                work = work.withColumn(colname, fail_expr)
                rule_meta.append((colname, f"referential_integrity[{check['column']}->{check['parent_table']}]", ri["severity"], ri.get("max_fail_rate", 0.0)))

    bad_masks = [m[0] for m in rule_meta]

    if bad_masks:
        any_fail = None
        for c in bad_masks:
            any_fail = F.col(c) if any_fail is None else (any_fail | F.col(c))
        work = work.withColumn("_any_fail", any_fail)
        

        agg_exprs = [F.count(F.lit(1)).alias("_total"), F.sum(F.col("_any_fail").cast("long")).alias("_total_bad")]
        agg_exprs += [F.sum(F.col(c).cast("long")).alias(c) for c in bad_masks]
        
        agg_row = work.agg(*agg_exprs).collect()[0]
        total = agg_row["_total"]
        report["row_count"] = total

        for colname, label, severity, max_fail_rate in rule_meta:
            bad_count = agg_row[colname] or 0
            rate = _fail_rate(bad_count, total)
            blocked = severity == "hard" and rate > max_fail_rate
            report["rule_results"].append({
                "rule": label,
                "severity": severity,
                "bad_count": bad_count,
                "fail_rate": round(rate, 4),
                "blocked": blocked
            })
            report["promotion_blocked"] = report["promotion_blocked"] or blocked

        reason_cols = [F.when(F.col(c), F.lit(c.replace("_fail_", ""))) for c in bad_masks]
        work = work.withColumn(
            "_quarantine_reasons", 
            F.array_join(F.array_except(F.array(*reason_cols), F.array(F.lit(None).cast("string"))), ";")
        )
        
        quarantined = work.filter(F.col("_any_fail")).drop(*bad_masks, "_any_fail")
        clean = work.filter(~F.col("_any_fail")).drop(*bad_masks, "_any_fail", "_quarantine_reasons")

        report["quarantined_count"] = agg_row["_total_bad"] or 0
        report["clean_count"] = total - report["quarantined_count"]
    else:
        total = work.count()
        report["row_count"] = total
        quarantined = work.limit(0)
        clean = work
        report["quarantined_count"] = 0
        report["clean_count"] = total

    return clean, quarantined, report


def summarize_reports(reports: List[Dict[str, Any]]) -> Dict[str, Any]:
    """Compile validation reports from multiple tables into a single summary."""
    return {
        "tables_validated": len(reports),
        "any_promotion_blocked": any(r["promotion_blocked"] for r in reports),
        "total_rows": sum(r["row_count"] for r in reports if r["row_count"] is not None),
        "total_quarantined": sum(r["quarantined_count"] for r in reports),
        "details": reports,
    }
