import sqlite3
from langgraph.checkpoint.serde.jsonplus import JsonPlusSerializer

def main():
    conn = sqlite3.connect("checkpoint_inspect.db")
    cursor = conn.cursor()
    
    cursor.execute("SELECT checkpoint_id, checkpoint_format, checkpoint_bytes FROM checkpoints ORDER BY checkpoint_id DESC LIMIT 1")
    row = cursor.fetchone()
    if row:
        cp_id, cp_fmt, cp_bytes = row
        serde = JsonPlusSerializer()
        cp_data = serde.loads_typed((cp_fmt, cp_bytes))
        channel_values = cp_data.get("channel_values", {})
        
        silver_code = channel_values.get("silver_code", "")
        gold_code = channel_values.get("gold_code", "")
        
        print("=== SILVER CODE GENERATED BY AGENT ===")
        print(silver_code)
        print("-" * 50)
        
        print("=== GOLD CODE GENERATED BY AGENT ===")
        print(gold_code)
        print("-" * 50)
            
    conn.close()

if __name__ == "__main__":
    main()
